stages:
  data_ingestion:
    cmd:
      - python3 src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw

  data_preprocessing:
    cmd:
      - python3 src/data_preprocessing.py
    deps:
      - data/raw
      - src/data_preprocessing.py
    outs:
      - data/interim

  feature_engineering:
    cmd:
      - python3 src/feature_engineering.py
    deps:
      - data/interim
      - src/feature_engineering.py
    outs:
      - data/processed

  model_training:
    cmd:
      - python3 src/model_training.py
    deps:
      - data/processed
      - src/model_training.py
    outs:
      - models/model.pkl

  model_evaluation:
    cmd:
      - python3 src/model_evaluation.py
    deps:
      - models/model.pkl
      - src/model_evaluation.py
    outs:
      - reports/metrics.json
